### PR TITLE
Add custom exception classes instead of using plain error types.

### LINKED ISSUE #8: Use locally defined exception classes instead of raising generic exception types.
Prompted by: https://github.com/netdata/netdata/pull/7024

This module appears to directly raise `ValueError` and `RuntimeError` under specific circumstances.  While both are technically accurate, they necessitate use of overly broad `except` clauses when dealing with error handling for the module, which makes it difficult to verify that code using the module is actually correct and can't accidentally hide other errors. The `RuntimeError` usage is particularly problematic, as it's very rare in the core language to ever catch a `RuntimeError`, so any code that catches one tends to look rather out of place to many people.

I would suggest switching to the same methodology that's used by much of the Python ecosystem of defining local sub-classes of `Exception` (or whatever specific error makes sense) and raising those instead of directly raising built-in exception types.

### PR DESCRIPTION
**Pull request by Ferroin**
This adds custom exception classes so that users do not have to match on generic exception types in code that uses this module.

The new custom classes are structured so that existing code that is matching on the generic exception types will still work, and so that there's a primary exception type that can be matched on to catch all
errors specific to this module.

----

Fixes: #8 

This is minimally tested right now (using `flake8` to check that there are no syntax errors or other obvious problems with the changes). I intend to test it further, but won't be able to until at least this evening, or possibly tomorrow evening.  I'll comment here again when I've finished proper testing.

### CODE REVIEW

**Comment by ladyada** [comment]
looks good! please let us know when you've tested this with hardware :)

**Comment by Ferroin** [comment]
> looks good! please let us know when you've tested this with hardware :)

I don't have actual hardware to test with, as mentioned in the issue this was prompted by review of a plugin for Netdata that uses this module to collect data from the hardware (relevant discussion that prompted this starts at https://github.com/netdata/netdata/pull/7024#discussion_r332570625).

However, I have now (now that I finally got time to do so) tested it using Linux's `i2c-stub` driver to simulate an AM2320 (configured to just return a static value for the temperature and humidity), and nothing appears to behave any different with or without the change (except of course for the type of the exceptions that get raised, and the memory usage (marginally higher, empty classes aren't free, but they're not particularly expensive either)).  I can't really confirm the I2C read error behavior this way though (at least, I'm pretty sure I can't, I don't think I can get the `i2c-stub` driver to simulate a read error), but the CRC mismatch and connection failure errors work correctly.

**Comment by ladyada** [comment]
ooh ok - we'll get to reviewing this later, hardware's tricky so we like to always test with physsical hardware :)

**Review by jepler — APPROVED** [review]
These changes look reasonable and should not affect existing code

**Comment by jerryneedell** [comment]
just an FYI -- I've reproduced this on a Grand Central and a Teensy 4.0..  It looks like this was never tested on hardware, correct? Did it ever work?  
Added more info in #15  -- works on RPi 4  -- will continue in the issue

**Pull request merged**
